name: Code formatting

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the main branch
  push: {}
  pull_request:
    branches: [main]

jobs:
  pre-commit-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        # for private repo - first is the checkout step, which needs to use unlimited fetch depth for pushing
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2

      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - uses: pre-commit/action@v2.0.3
        # this action also provides an additional behaviour when used in private repositories
        # when configured with a github token, the action will push back fixes to the pull request branch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
